export type Plan = {
  name: string
  price: string
  period: string
  badge?: string
  features: string[]
  cta: string
  popular?: boolean
}

export type Module = {
  name: string
  icon: string
  desc: string
}

export type Service = {
  id: string
  title: string
  shortTitle: string
  tagline: string
  description: string
  icon: string
  color: string
  gradient: string
  category: string
  available: boolean
  stats?: { label: string; value: string }[]
  features?: string[]
  modules?: Module[]
  plans?: Plan[]
}

export const SERVICES: Service[] = [
  {
    id: 'school-erp',
    title: 'School ERP',
    shortTitle: 'School ERP',
    tagline: 'Complete School Management System',
    description: 'End-to-end digital management for schools — from admissions to alumni. Automate attendance, fees, exams, timetable, communication and more.',
    icon: '🎓',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
    category: 'Education',
    available: true,
    stats: [
      { label: 'Schools Active', value: '120+' },
      { label: 'Students Managed', value: '50K+' },
      { label: 'Uptime SLA', value: '99.9%' },
    ],
    features: [
      'Smart Admission Management',
      'Real-time Attendance Tracking',
      'Fee Collection & Receipts',
      'Exam & Result Management',
      'Timetable Scheduling',
      'Teacher & Staff Management',
      'Parent Communication Portal',
      'WhatsApp Notifications',
      'AI-powered Analytics',
      'Multi-branch Support',
      'Mobile App for Parents',
      'Cloud Backup & Security',
    ],
    modules: [
      { name: 'Admissions', icon: '📋', desc: 'Online inquiry to enrollment' },
      { name: 'Attendance', icon: '✅', desc: 'Biometric & manual tracking' },
      { name: 'Fee Management', icon: '💳', desc: 'Online & offline payments' },
      { name: 'Examination', icon: '📝', desc: 'Create, publish & analyze' },
      { name: 'Timetable', icon: '📅', desc: 'Drag & drop scheduler' },
      { name: 'Library', icon: '📚', desc: 'Catalog & circulation mgmt' },
      { name: 'Transport', icon: '🚌', desc: 'GPS-tracked bus routes' },
      { name: 'Hostel', icon: '🏠', desc: 'Room & fee management' },
      { name: 'HR & Payroll', icon: '👥', desc: 'Staff salary & leaves' },
      { name: 'Reports & AI', icon: '📊', desc: 'Smart insights dashboard' },
      { name: 'Parent Portal', icon: '👨‍👩‍👧', desc: 'Real-time progress access' },
      { name: 'WhatsApp Bot', icon: '💬', desc: 'Automated parent alerts' },
    ],
    plans: [
      {
        name: 'Basic',
        price: '₹1,799',
        period: '/month',
        features: [
          'Up to 200 Students',
          '1 Admin Account',
          'Weekly Customer Support',
          'Student Management',
          'Attendance Tracking',
          'Fee Management',
          'Result Management',
          'Basic Reports',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional',
        price: '₹2,999',
        period: '/month',
        badge: 'Most Popular',
        popular: true,
        features: [
          'Everything in Basic',
          'HRMS Module Included',
          '200–500 Students',
          '3 Admin Accounts',
          '24/7 Support',
          'Teacher Management',
          'Payroll System',
          'Advanced Analytics',
          'Role-based Access',
        ],
        cta: 'Start Free Trial',
      },
      {
        name: 'Enterprise',
        price: '₹5,999',
        period: '/month',
        features: [
          'Everything in Professional',
          'WhatsApp Notifications',
          '500+ Students',
          '5 Admin Accounts',
          '24/7 Priority Support',
          'AI-powered Reports',
          'Cloud ERP Dashboard',
          'Custom Integrations',
          'Advanced Security',
          'Real-time Alerts',
        ],
        cta: 'Contact Sales',
      },
    ],
  },
  {
    id: 'college-erp',
    title: 'College ERP',
    shortTitle: 'College ERP',
    tagline: 'Higher Education Management Platform',
    description: 'Advanced ERP for colleges and universities. Manage departments, courses, credits, research, placements, and accreditation compliance.',
    icon: '🏛️',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-700',
    category: 'Education',
    available: false,
    features: [
      'Department & Course Management',
      'Credit & Semester System',
      'Placement Portal',
      'Research & Grant Tracking',
      'Alumni Management',
      'NAAC/NBA Compliance Reports',
    ],
    plans: [],
  },
  {
    id: 'hrms',
    title: 'Human Resource Management',
    shortTitle: 'HRMS',
    tagline: 'Smart HR for Modern Organizations',
    description: 'Streamline HR operations — recruitment, onboarding, attendance, payroll, performance, and compliance — in one unified platform.',
    icon: '👥',
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-cyan-600',
    category: 'Business',
    available: false,
    features: [
      'Recruitment & ATS',
      'Employee Onboarding',
      'Attendance & Leave',
      'Payroll Automation',
      'Performance Reviews',
      'Compliance Management',
    ],
    plans: [],
  },
  {
    id: 'inventory',
    title: 'Inventory Management',
    shortTitle: 'Inventory',
    tagline: 'Real-time Stock Intelligence',
    description: 'Track stock across warehouses, automate reorders, manage suppliers, and reduce wastage with AI-driven inventory insights.',
    icon: '📦',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    category: 'Business',
    available: false,
    features: [
      'Multi-warehouse Tracking',
      'Automated Reorder Points',
      'Supplier Management',
      'Barcode / QR Scanning',
      'Stock Valuation',
      'Real-time Dashboards',
    ],
    plans: [],
  },
  {
    id: 'sales-erp',
    title: 'Sales ERP',
    shortTitle: 'Sales ERP',
    tagline: 'Close More Deals, Faster',
    description: 'End-to-end CRM & Sales ERP — lead tracking, quotation, invoicing, pipeline management and AI-powered forecasting.',
    icon: '📈',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    category: 'Business',
    available: false,
    features: [
      'Lead & Deal Pipeline',
      'Quotation & Invoice',
      'Customer Portal',
      'AI Sales Forecasting',
      'Team Performance',
      'Territory Management',
    ],
    plans: [],
  },
  {
    id: 'whatsapp-automation',
    title: 'WhatsApp Automation',
    shortTitle: 'WhatsApp',
    tagline: 'Engage Customers at Scale via WhatsApp',
    description: 'Automate customer communication, marketing broadcasts, order updates, appointment reminders and chatbots via WhatsApp Business API.',
    icon: '💬',
    color: '#25d366',
    gradient: 'from-green-500 to-emerald-600',
    category: 'Automation',
    available: false,
    features: [
      'WhatsApp Business API',
      'Bulk Broadcast Campaigns',
      'Chatbot Flows',
      'Order / Appointment Alerts',
      'Two-way Messaging',
      'Analytics Dashboard',
    ],
    plans: [],
  },
  {
    id: 'hospital-opd',
    title: 'Hospital OPD Management',
    shortTitle: 'Hospital OPD',
    tagline: 'Digitize Your OPD in 24 Hours',
    description: 'Modern OPD management — patient registration, doctor scheduling, prescription, billing, lab reports and insurance integration.',
    icon: '🏥',
    color: '#ef4444',
    gradient: 'from-red-500 to-rose-600',
    category: 'Healthcare',
    available: false,
    features: [
      'Patient Registration',
      'Doctor Scheduling',
      'Digital Prescriptions',
      'OPD Billing',
      'Lab Integration',
      'Insurance Claims',
    ],
    plans: [],
  },
  {
    id: 'website-development',
    title: 'Dynamic Website Development',
    shortTitle: 'Web Dev',
    tagline: 'Enterprise Websites that Convert',
    description: 'Custom Next.js / React websites with CMS, SEO optimization, e-commerce, and AI-powered features for enterprises and startups.',
    icon: '🌐',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
    category: 'Development',
    available: false,
    features: [
      'Next.js / React Websites',
      'CMS Integration',
      'E-Commerce Solutions',
      'SEO Optimization',
      'AI Chatbot Integration',
      'Mobile Responsive',
    ],
    plans: [],
  },
  {
    id: 'digital-transformation',
    title: 'Digital Transformation Services',
    shortTitle: 'Digital Transform',
    tagline: 'Modernize Your Entire Business',
    description: 'End-to-end digital transformation consulting — process automation, cloud migration, AI adoption, data analytics and change management.',
    icon: '⚡',
    color: '#f97316',
    gradient: 'from-orange-500 to-red-600',
    category: 'Consulting',
    available: false,
    features: [
      'Process Assessment',
      'Cloud Migration',
      'AI Adoption Roadmap',
      'Data Analytics Setup',
      'Change Management',
      'ROI Tracking',
    ],
    plans: [],
  },
  {
    id: 'custom-cloud-erp',
    title: 'Custom Cloud ERP',
    shortTitle: 'Custom ERP',
    tagline: 'Built Exactly for Your Business',
    description: 'We build bespoke Cloud ERP systems from scratch — tailored modules, white-label options, custom APIs and dedicated cloud infrastructure.',
    icon: '☁️',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-blue-600',
    category: 'Development',
    available: false,
    features: [
      'Custom Module Development',
      'White-label ERP',
      'Cloud Deployment',
      'API Integrations',
      'Dedicated Support',
      'Pay-as-you-grow',
    ],
    plans: [],
  },
  {
    id: 'payg-erp',
    title: 'Pay-as-you-go ERP',
    shortTitle: 'PAYG ERP',
    tagline: 'Start Small, Scale Infinitely',
    description: 'Zero upfront cost ERP. Pay only for the modules you use, scale up as you grow. Perfect for startups and growing businesses.',
    icon: '💰',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-indigo-600',
    category: 'Business',
    available: false,
    features: [
      'Zero Setup Cost',
      'Pay Per Module',
      'Instant Activation',
      'Scale On-demand',
      'No Long-term Lock-in',
      'Usage-based Billing',
    ],
    plans: [],
  },
  {
    id: 'ai-automation',
    title: 'AI Business Automation',
    shortTitle: 'AI Automation',
    tagline: 'Let AI Run Your Business Operations',
    description: 'Harness the power of Gemini, GPT and custom AI models to automate workflows, generate reports, predict demand and drive decisions.',
    icon: '🤖',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
    category: 'AI',
    available: false,
    features: [
      'AI Workflow Automation',
      'Predictive Analytics',
      'AI Report Generation',
      'Demand Forecasting',
      'Intelligent Chatbots',
      'Document Intelligence',
    ],
    plans: [],
  },
]

export const STATS = [
  { value: '500+', label: 'Institutions Served' },
  { value: '1.2L+', label: 'Students Managed' },
  { value: '99.9%', label: 'Uptime Guarantee' },
  { value: '12+', label: 'ERP Modules' },
]

export const TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    role: 'Principal',
    org: 'Delhi Public Academy',
    avatar: 'PS',
    text: 'OmniSphere 365 completely transformed how we manage our school. Fee collection, attendance, and parent communication — all automated. Our staff saves 4 hours every day.',
    rating: 5,
  },
  {
    name: 'Rajesh Gupta',
    role: 'CEO',
    org: 'EduTech Solutions',
    avatar: 'RG',
    text: "The School ERP's AI analytics gave us insights we never had before. Enrollment went up 30% after we could actually see where students were dropping off.",
    rating: 5,
  },
  {
    name: 'Anita Verma',
    role: 'Director',
    org: 'Modern Public School, Noida',
    avatar: 'AV',
    text: 'Implementation was smooth, support is excellent, and the WhatsApp notifications feature is a game-changer for parent engagement. Highly recommend.',
    rating: 5,
  },
]

export const WHY_US = [
  { icon: '☁️', title: 'Cloud Infrastructure', desc: 'AWS-grade cloud hosting with 99.9% uptime SLA and auto-scaling for any load.' },
  { icon: '🤖', title: 'AI Integration', desc: 'Built-in AI for smart reports, predictions, and workflow automation.' },
  { icon: '🔒', title: 'Secure Platform', desc: 'End-to-end encryption, role-based access, and ISO-compliant data security.' },
  { icon: '🛟', title: '24/7 Support', desc: 'Dedicated support engineers available round the clock via chat, email, and phone.' },
  { icon: '🔧', title: 'Custom ERP', desc: 'Every solution tailored to your exact business workflows and requirements.' },
  { icon: '📈', title: 'Scalable Systems', desc: 'Start small and scale to enterprise-grade without changing your platform.' },
  { icon: '📊', title: 'Real-time Analytics', desc: 'Live dashboards and AI-driven insights for faster, smarter decisions.' },
  { icon: '🛡️', title: 'Enterprise Security', desc: 'Multi-layer security, audit logs, and compliance-ready infrastructure.' },
  { icon: '⚡', title: 'Automation-first', desc: 'Eliminate manual tasks with intelligent automation across every module.' },
]

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'How School ERP is Transforming Education in India',
    excerpt: 'Discover how modern school management systems are reducing admin work by 70% and improving parent engagement.',
    category: 'Education',
    date: 'June 2025',
    readTime: '5 min read',
    icon: '🎓',
  },
  {
    id: 2,
    title: 'AI in ERP: What Every Business Leader Needs to Know',
    excerpt: 'AI is no longer optional in enterprise software. Learn how OmniSphere 365 embeds AI across every module.',
    category: 'AI & Tech',
    date: 'May 2025',
    readTime: '7 min read',
    icon: '🤖',
  },
  {
    id: 3,
    title: 'Pay-as-you-go ERP: The Future for SMBs',
    excerpt: 'Why subscription-based, modular ERP is the smartest choice for growing businesses in 2025.',
    category: 'Business',
    date: 'May 2025',
    readTime: '4 min read',
    icon: '💰',
  },
  {
    id: 4,
    title: 'WhatsApp Automation for Schools: Complete Guide',
    excerpt: 'Step-by-step guide to automating parent communication, fee reminders, and exam alerts via WhatsApp.',
    category: 'Automation',
    date: 'April 2025',
    readTime: '6 min read',
    icon: '💬',
  },
]

export const OPEN_ROLES = [
  { title: 'Full Stack Developer', dept: 'Engineering', type: 'Full-time', location: 'Delhi / Remote', stack: 'React, Node.js, Python' },
  { title: 'React Developer', dept: 'Frontend', type: 'Full-time', location: 'Delhi / Remote', stack: 'React, Next.js, TypeScript' },
  { title: 'ERP Consultant', dept: 'Product', type: 'Full-time', location: 'Delhi', stack: 'ERP, Business Analysis' },
  { title: 'AI Engineer', dept: 'AI/ML', type: 'Full-time', location: 'Remote', stack: 'Python, LLMs, ML' },
  { title: 'Sales Executive', dept: 'Sales', type: 'Full-time', location: 'Delhi', stack: 'B2B SaaS Sales' },
  { title: 'UI/UX Designer', dept: 'Design', type: 'Full-time', location: 'Delhi / Remote', stack: 'Figma, Framer, Design Systems' },
  { title: 'Frontend Intern', dept: 'Engineering', type: 'Internship', location: 'Remote', stack: 'React, Tailwind CSS' },
  { title: 'Marketing Intern', dept: 'Marketing', type: 'Internship', location: 'Delhi', stack: 'Content, SEO, Social Media' },
]
