export type Plan = {
  name: string
  price: string
  period: string
  badge?: string
  features: string[]
  cta: string
  popular?: boolean
}

export type Module = {
  name: string
  icon: string
  desc: string
}

export type Service = {
  id: string
  title: string
  shortTitle: string
  tagline: string
  description: string
  icon: string
  color: string
  gradient: string
  category: string
  available: boolean
  stats?: { label: string; value: string }[]
  features?: string[]
  modules?: Module[]
  plans?: Plan[]
}

export const SERVICES: Service[] = [
  {
    id: 'school-erp',
    title: 'School ERP',
    shortTitle: 'School ERP',
    tagline: 'Complete School Management System',
    description: 'End-to-end digital management for K-12 schools — from smart admissions to alumni. Automate attendance, fees, exams, timetable, and parent communication.',
    icon: '🎓',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
    category: 'Education',
    available: true,
    stats: [
      { label: 'Schools Active', value: '120+' },
      { label: 'Students & Staff', value: '50K+' },
      { label: 'Uptime SLA', value: '99.9%' },
    ],
    features: [
      'Smart Admission Management',
      'Real-time Biometric Attendance',
      'Online Fee Collection & Receipts',
      'Exam & Result Management',
      'Automated Timetable Scheduling',
      'Teacher & Staff Management',
      'Parent Communication Portal',
      'WhatsApp Notifications',
      'AI-powered Analytics',
      'Multi-branch Support',
      'Mobile App for Parents',
      'Cloud Backup & Security',
    ],
    modules: [
      { name: 'Admissions', icon: '📋', desc: 'Online inquiry to enrollment' },
      { name: 'Attendance', icon: '✅', desc: 'Biometric & manual tracking' },
      { name: 'Fee Management', icon: '💳', desc: 'Online & offline payments' },
      { name: 'Examination', icon: '📝', desc: 'Create, publish & analyze' },
      { name: 'Timetable', icon: '📅', desc: 'Drag & drop scheduler' },
      { name: 'Library', icon: '📚', desc: 'Catalog & circulation mgmt' },
      { name: 'Transport', icon: '🚌', desc: 'GPS-tracked bus routes' },
      { name: 'Hostel', icon: '🏠', desc: 'Room & fee management' },
      { name: 'HR & Payroll', icon: '👥', desc: 'Staff salary & leaves' },
      { name: 'Reports & AI', icon: '📊', desc: 'Smart insights dashboard' },
      { name: 'Parent Portal', icon: '👨‍👩‍👧', desc: 'Real-time progress access' },
      { name: 'WhatsApp Bot', icon: '💬', desc: 'Automated parent alerts' },
    ],
    plans: [
      {
        name: 'Starter Tier',
        price: '₹1,799',
        period: '/month',
        features: [
          'Up to 200 Students / Users',
          '1 Admin Account',
          'Standard Support',
          'Student & Profile Master',
          'Attendance Tracking',
          'Fee Management & Receipts',
          'Exam & Result Generator',
          'Basic Reports',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional',
        price: '₹2,999',
        period: '/month',
        badge: 'Most Popular',
        popular: true,
        features: [
          'Everything in Starter',
          'HRMS & Payroll Module',
          '200–500 Students / Users',
          '3 Admin Accounts',
          '24/7 Priority Support',
          'Staff Salary Slips',
          'Biometric Machine Sync',
          'Advanced Analytics',
          'Role-based Permissions',
        ],
        cta: 'Start Free Trial',
      },
      {
        name: 'Enterprise Scale',
        price: '₹5,999',
        period: '/month',
        features: [
          'Everything in Professional',
          'Official WhatsApp Business API',
          '500+ Students / Users',
          'Unlimited Admin Accounts',
          '24/7 Priority Dedicated Manager',
          'AI-Powered Predictive Reports',
          'Multi-branch Multi-Tenant Control',
          'Custom Integrations & APIs',
          'Direct Bank Payout Reconciliation',
          'Real-time WhatsApp Alerts',
        ],
        cta: 'Contact Sales',
      },
    ],
  },
  {
    id: 'college-erp',
    title: 'College & University ERP',
    shortTitle: 'University ERP',
    tagline: 'Higher Education Management Platform',
    description: 'Advanced multi-department ERP for colleges, universities and polytechnics. Manage departments, credits, semester exams, research, placements, and NAAC compliance.',
    icon: '🏛️',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-700',
    category: 'Education',
    available: true,
    features: [
      'Department & Course Management',
      'Credit & Choice-Based Grading (CBCS)',
      'Campus Placement & Training Portal',
      'Faculty Research & Grant Tracking',
      'Alumni Engagement Network',
      'NAAC/NBA Compliance Reports',
    ],
    plans: [],
  },
  {
    id: 'hrms',
    title: 'Smart HRMS & Global Payroll',
    shortTitle: 'Smart HRMS',
    tagline: 'Workforce Intelligence for Modern Enterprises',
    description: 'Streamline complete HR operations — recruitment, onboarding, multi-shift biometric attendance, salary disbursals, PF/ESI/TDS tax compliance, and performance appraisals.',
    icon: '👥',
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-cyan-600',
    category: 'Business',
    available: true,
    features: [
      'Recruitment Pipeline & ATS',
      'Digital Employee Onboarding',
      'Multi-Shift Biometric Attendance',
      '1-Click Automated Payroll Disbursal',
      'TDS, PF & ESI Statutory Compliance',
      'KPI & OKR Performance Reviews',
    ],
    plans: [],
  },
  {
    id: 'hospital-opd',
    title: 'Hospital & Clinic OPD Management',
    shortTitle: 'Hospital OPD',
    tagline: 'Digitize Hospital OPD & Clinical Operations',
    description: 'Modern hospital and clinic operating system — patient electronic records (EMR), doctor queue scheduling, digital prescriptions, OPD billing, pathology lab reports, and pharmacy POS.',
    icon: '🏥',
    color: '#ef4444',
    gradient: 'from-red-500 to-rose-600',
    category: 'Healthcare',
    available: true,
    features: [
      'Patient Registration & EMR Masters',
      'Doctor Token & Queue Scheduling',
      'Digital E-Prescriptions & Diagnosis',
      'OPD & IPD Billing with GST Invoicing',
      'Pathology Lab & Diagnostic Reports',
      'Pharmacy POS & Stock Inventory',
    ],
    plans: [],
  },
  {
    id: 'gym-management',
    title: 'Gym & Fitness Center Management',
    shortTitle: 'Gym ERP',
    tagline: 'End-to-End Gym & Fitness Studio ERP',
    description: 'Comprehensive fitness center software — membership subscriptions, biometric & RFID turnstile access control, trainer scheduling, automated WhatsApp renewal reminders, and POS supplement sales.',
    icon: '💪',
    color: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
    category: 'Wellness',
    available: true,
    features: [
      'Membership Plans & Auto-Renewals',
      'Biometric & RFID Turnstile Gate Sync',
      'Trainer Scheduling & Diet Charts',
      'Locker & Facility Allocation',
      'Supplement POS & Stock Billing',
      'WhatsApp Expiry & Payment Alerts',
    ],
    plans: [],
  },
  {
    id: 'inventory',
    title: 'Inventory & Supply Chain',
    shortTitle: 'Inventory & POS',
    tagline: 'Real-time Multi-Warehouse Intelligence',
    description: 'Track stock across multi-location warehouses, automate purchase reorders, manage suppliers, generate barcode labels, and eliminate inventory shrinkage with AI insights.',
    icon: '📦',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    category: 'Business',
    available: true,
    features: [
      'Multi-Warehouse Real-Time Tracking',
      'Automated Min-Max Reorder Points',
      'Vendor & Supplier Management',
      'Barcode & QR Code Scanning',
      'FIFO / LIFO Stock Valuation',
      'Integrated Retail POS Billing',
    ],
    plans: [],
  },
  {
    id: 'sales-erp',
    title: 'Sales CRM & Invoicing',
    shortTitle: 'Sales CRM',
    tagline: 'Close Deals Faster with Automated Pipelines',
    description: 'End-to-end B2B and B2C CRM & Sales ERP — lead tracking, quotations, GST invoicing, revenue pipeline management, customer portal, and AI-powered sales forecasting.',
    icon: '📈',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    category: 'Business',
    available: true,
    features: [
      'Lead & Deal Pipeline Management',
      '1-Click GST Quotations & Invoices',
      'Client Self-Service Portal',
      'AI Revenue Forecasting',
      'Sales Rep Target & Commission Tracking',
      'Territory & Branch Management',
    ],
    plans: [],
  },
  {
    id: 'ai-automation',
    title: 'Agentic AI Business Automation',
    shortTitle: 'AI Automation',
    tagline: 'Autonomous AI for Every Business Routine',
    description: 'Harness the power of autonomous AI models to automate administrative workflows, auto-generate business reports, trigger smart dues recovery, and predict operational demand.',
    icon: '🤖',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
    category: 'AI',
    available: true,
    features: [
      'Autonomous Workflow Triggers',
      'AI Dues Recovery & Follow-up Scheduling',
      'Predictive Business & Demand Analytics',
      'Automated Multi-Tenant Report Generation',
      'Document Intelligence & OCR Invoicing',
      '24/7 Multi-Language Conversational Bots',
    ],
    plans: [],
  },
  {
    id: 'whatsapp-automation',
    title: 'WhatsApp Business Cloud Hub',
    shortTitle: 'WhatsApp Hub',
    tagline: 'Engage Customers & Members at Scale',
    description: 'Official Meta-verified WhatsApp Cloud API integration for instant billing alerts, payment receipts, circulars, customer support, and high-conversion broadcast marketing.',
    icon: '💬',
    color: '#25d366',
    gradient: 'from-green-500 to-emerald-600',
    category: 'Automation',
    available: true,
    features: [
      'Official Meta Verified Green Badge API',
      'Automated In-Chat Payment Links & PDF Receipts',
      'Bulk Segmented Broadcast Campaigns',
      'Interactive 24/7 AI Chatbot Flows',
      'Two-Way Support Ticket Routing',
      'Real-time Message Delivery & Read Analytics',
    ],
    plans: [],
  },
  {
    id: 'custom-cloud-erp',
    title: 'Custom Multi-Tenant Cloud ERP',
    shortTitle: 'Custom Cloud ERP',
    tagline: 'Engineered Exactly for Your Enterprise Workflow',
    description: 'Bespoke multi-tenant Cloud ERP systems engineered from scratch — tailored database models, white-label branding, custom REST APIs, and dedicated high-availability cloud infrastructure.',
    icon: '☁️',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-blue-600',
    category: 'Development',
    available: true,
    features: [
      'Custom Multi-Tenant Architecture',
      'White-label Brand Customization',
      'Dedicated AWS/GCP Cloud Deployment',
      'Custom Third-Party API Integrations',
      'Dedicated Solution Support Architect',
      'Flexible Pay-as-you-grow Scalability',
    ],
    plans: [],
  },
  {
    id: 'payg-erp',
    title: 'Pay-As-You-Go Modular ERP',
    shortTitle: 'PAYG ERP',
    tagline: 'Start Modular, Scale Infinitely',
    description: 'Zero upfront license fees. Pay only for the specific modules and user tiers you use, scale up or down as your business expands.',
    icon: '💰',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-indigo-600',
    category: 'Business',
    available: true,
    features: [
      'Zero Upfront Setup Cost',
      'Pay Per Active Module / Month',
      'Instant Cloud Activation in 60s',
      'Scale Seats On-Demand',
      'No Long-Term Lock-in Contracts',
      'Unified Master Dashboard',
    ],
    plans: [],
  },
  {
    id: 'digital-transformation',
    title: 'Enterprise Digital Transformation',
    shortTitle: 'Digital Transform',
    tagline: 'Modernize Legacy Operations Across India',
    description: 'Full-spectrum enterprise transformation consulting — legacy software migration, paperless operations, cloud modernization, and AI workflow integration.',
    icon: '⚡',
    color: '#f97316',
    gradient: 'from-orange-500 to-red-600',
    category: 'Consulting',
    available: true,
    features: [
      'Operational Process Assessment',
      'Legacy System to Cloud Migration',
      'AI & Automation Implementation Roadmap',
      'Centralized BI Analytics Setup',
      'Change Management & Staff Training',
      'Clear Measurable ROI Benchmarks',
    ],
    plans: [],
  },
  {
    id: 'website-development',
    title: 'Dynamic Web & Mobile Portals',
    shortTitle: 'Web & Mobile Dev',
    tagline: 'Enterprise-Grade Portals and Apps',
    description: 'Next.js & React native web applications, member portals, student/patient mobile apps with role-based access, fast load times, and bank-grade security.',
    icon: '🌐',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
    category: 'Development',
    available: true,
    features: [
      'Next.js 14 Server-Side Rendered Portals',
      'Native-Like Mobile PWA & Apps',
      'Role-Based Secure Customer Portals',
      'Payment Gateway Integration',
      'High-Performance SEO Architecture',
      'Real-Time WebSocket Notifications',
    ],
    plans: [],
  },
]

export const STATS = [
  { value: '500+', label: 'Enterprises & Institutions' },
  { value: '2.5M+', label: 'Active Users & Members' },
  { value: '99.9%', label: 'Uptime SLA Guarantee' },
  { value: '15+', label: 'Multi-Tenant Modules' },
]

export const TESTIMONIALS = [
  {
    name: 'Dr. Sameer Alvi',
    role: 'Managing Director',
    org: 'Apex Healthcare & Clinics',
    avatar: 'SA',
    text: 'OnePlatform360 digitized our hospital OPD in 48 hours. Patient queues, digital prescriptions, lab reports, and billing are completely synchronized. Outstanding multi-tenant architecture!',
    rating: 5,
  },
  {
    name: 'Vikram Singhania',
    role: 'Founder & COO',
    org: 'FitPulse 360 Gym Network',
    avatar: 'VS',
    text: 'Managing 6 gym branches with 4,200 members used to be chaos. With OnePlatform360 Gym ERP, turnstile biometrics, membership renewals, and WhatsApp reminders run 100% on autopilot.',
    rating: 5,
  },
  {
    name: 'Priya Sharma',
    role: 'Principal',
    org: 'Delhi Public Academy',
    avatar: 'PS',
    text: 'Fee collection, biometric attendance, report cards, and parent WhatsApp circulars — all automated seamlessly. Our academic staff saves over 4 hours every single day.',
    rating: 5,
  },
  {
    name: 'Rajesh Gupta',
    role: 'VP Operations',
    org: 'Nexus Retail & Logistics',
    avatar: 'RG',
    text: 'The multi-warehouse inventory, POS billing, and smart HRMS payroll integration transformed our supply chain. Real-time visibility on stock and staff across 12 locations.',
    rating: 5,
  },
]

export const WHY_US = [
  { icon: '☁️', title: 'Multi-Tenant Cloud', desc: 'AWS/GCP enterprise infrastructure with 99.9% uptime SLA and multi-branch tenant isolation.' },
  { icon: '🤖', title: 'Agentic AI Workflows', desc: 'Built-in AI for smart fee recovery, predictive analytics, auto-reports, and operational forecasting.' },
  { icon: '🔒', title: 'Bank-Grade Security', desc: 'End-to-end 256-bit encryption, granular role-based permissions, and ISO-compliant data safety.' },
  { icon: '🛟', title: '24/7 Dedicated Support', desc: 'Dedicated solution architects and technical support available round the clock.' },
  { icon: '🔧', title: 'Modular Architecture', desc: 'Enable School ERP, Hospital OPD, Gyms, HRMS, or Inventory independently or unified.' },
  { icon: '📈', title: 'Infinite Scalability', desc: 'Start with 50 users and scale seamlessly to 500,000+ without changing your software platform.' },
  { icon: '📊', title: 'Real-time BI Dashboards', desc: 'Executive visibility, revenue reconciliation, and instant multi-branch performance metrics.' },
  { icon: '🛡️', title: 'Statutory Compliance', desc: 'Built-in support for Indian GST, TDS, PF, ESI, CBSE/ICSE academic standards, and healthcare EMRs.' },
  { icon: '⚡', title: 'Meta WhatsApp Hub', desc: 'Official Green-Badge WhatsApp Business API for instant circulars, payment links, and alerts.' },
]

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'Why Multi-Tenant Cloud ERP is the Future for Indian Businesses & Institutions',
    excerpt: 'How modern organizations are eliminating siloed software by moving Schools, HRMS, Hospital OPDs, and Gyms onto a single unified operating platform.',
    category: 'Multi-Tenant ERP',
    date: 'June 2026',
    readTime: '5 min read',
    icon: '☁️',
  },
  {
    id: 2,
    title: 'AI in Enterprise ERP: Slashing Administrative Costs by 72%',
    excerpt: 'How autonomous AI agents automate billing recovery, biometric attendance reconciliations, and instant report generation.',
    category: 'AI & Tech',
    date: 'May 2026',
    readTime: '7 min read',
    icon: '🤖',
  },
  {
    id: 3,
    title: 'Modernizing Hospital OPDs & Clinic Workflows in 24 Hours',
    excerpt: 'Step-by-step blueprint for moving from paper registers to digital EMRs, token queue management, and automated patient WhatsApp receipts.',
    category: 'Healthcare',
    date: 'May 2026',
    readTime: '5 min read',
    icon: '🏥',
  },
  {
    id: 4,
    title: 'Gym & Fitness Studio Management: Scaling Multi-Branch Membership',
    excerpt: 'How turnstile biometric integration, trainer scheduling, and automated WhatsApp subscription renewals prevent revenue leaks.',
    category: 'Wellness',
    date: 'April 2026',
    readTime: '4 min read',
    icon: '💪',
  },
]

export const OPEN_ROLES = [
  { title: 'Full Stack ERP Engineer', dept: 'Engineering', type: 'Full-time', location: 'Delhi / Remote', stack: 'React, Node.js, Python, PostgreSQL' },
  { title: 'Senior Frontend Architect', dept: 'Frontend', type: 'Full-time', location: 'Delhi / Remote', stack: 'Next.js 14, TypeScript, Tailwind' },
  { title: 'ERP Solution Consultant', dept: 'Product', type: 'Full-time', location: 'Delhi', stack: 'Enterprise ERP, Multi-Tenant SaaS' },
  { title: 'AI/ML Agent Engineer', dept: 'AI/ML', type: 'Full-time', location: 'Remote', stack: 'Python, LLMs, LangChain, FastAPI' },
  { title: 'Enterprise Sales Manager', dept: 'Sales', type: 'Full-time', location: 'Delhi NCR', stack: 'B2B SaaS, Institutional Sales' },
  { title: 'UI/UX Product Designer', dept: 'Design', type: 'Full-time', location: 'Delhi / Remote', stack: 'Figma, Design Systems, Framer' },
  { title: 'Frontend Engineering Intern', dept: 'Engineering', type: 'Internship', location: 'Remote', stack: 'React, Next.js, Tailwind CSS' },
  { title: 'Product Marketing Associate', dept: 'Marketing', type: 'Full-time', location: 'Delhi', stack: 'Content, B2B Growth, SaaS SEO' },
]
